spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my-best-project-280823
    password: 21022002
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: havumadridista2102